services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"

  price_collector_celery:
    build:
      context: ./price-collector
    container_name: price_collector_celery
    depends_on:
      - mongo
      - redis
    environment:
      - CONNECTION_ALIAS=${CONNECTION_ALIAS}
      - MONGO_URI=${MONGO_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: bash -c "watchmedo auto-restart --directory=./app/celery_worker --pattern='*.py' --recursive -- celery -A app.celery_worker.worker worker --loglevel=info --pool=solo"
    volumes:
      - ./price-collector:/app

  price_collector:
    build:
      context: ./price-collector
      dockerfile: Dockerfile
    container_name: price_collector
    depends_on:
      - mongo
    environment:
      - CONNECTION_ALIAS=${CONNECTION_ALIAS}
      - MONGO_URI=${MONGO_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - COLLECTOR_IP=${COLLECTOR_IP}
      - COLLECTOR_PORT=${COLLECTOR_PORT}
      - COLLECTOR_SERVER_NAME=${COLLECTOR_SERVER_NAME}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
    volumes:
      - ./price-collector:/app
    ports:
      - "37967:37967"

volumes:
  mongodb_data:
