services:
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "${CELERY_PORT}:${CELERY_PORT}"
    networks:
      - ${NETWORK_NAME}

  beat:
    build:
      context: .
    container_name: celery-beat
    depends_on:
      - redis
    command: celery -A app.beat beat --loglevel=info
    networks:
      - ${NETWORK_NAME}
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - .:/app

  celery_worker:
    build:
      context: .
    container_name: celery-worker
    depends_on:
      - redis
    networks:
      - ${NETWORK_NAME}
    environment:
      - MONGO_BASE_URI=${MONGO_BASE_URI}
      - STOCKDB_ALIAS=${STOCKDB_ALIAS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - PYTHONPATH=/price_collector/app:/app:$PYTHONPATH
    command: bash -c "watchmedo auto-restart --directory=./app --pattern='*.py' --recursive -- celery -A app.worker worker --loglevel=info --pool=solo"
    volumes:
      - .:/app
      - ../price_collector:/price_collector

networks:
  moneylab_db:
    external: true

