services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - moneylab_db
    volumes:
      - db_data:/data/db

networks:
  moneylab_db:
    name: moneylab_db
    driver: bridge

volumes:
  db_data:
