services:
  mongo:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - db_data:/data/db

networks:
  moneylab_db:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  db_data:
