services:
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - ${NETWORK_NAME}

  price_collector_celery:
    build:
      context: .
    container_name: price_collector_celery
    depends_on:
      - redis
    networks:
      - ${NETWORK_NAME}
    environment:
      - MONGO_BASE_URI=${MONGO_BASE_URI}
      - STOCKDB_ALIAS=${STOCKDB_ALIAS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: bash -c "watchmedo auto-restart --directory=./app --pattern='*.py' --recursive -- celery -A app.celery_worker.worker worker --loglevel=info --pool=solo"
    volumes:
      - .:/app

  price_collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price_collector
    networks:
      - ${NETWORK_NAME}
    environment:
      - MONGO_BASE_URI=${MONGO_BASE_URI}
      - STOCKDB_ALIAS=${STOCKDB_ALIAS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - COLLECTOR_IP=${COLLECTOR_IP}
      - COLLECTOR_PORT=${COLLECTOR_PORT}
      - COLLECTOR_SERVER_NAME=${COLLECTOR_SERVER_NAME}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
    volumes:
      - .:/app
    ports:
      - "${COLLECTOR_PORT}:${COLLECTOR_PORT}"
    command: python main.py

networks:
  moneylab_db:
    external: true

