services:
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "${CELERY_PORT}:${CELERY_PORT}"
    networks:
      - redis-network
    volumes:
      - redis-data:/data


networks:
  redis-network:
    name: redis-network
    driver: bridge

volumes:
  redis-data:
